### ISSUE TITLE
add/remove property/values from variables

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-brand#25]
The variables are permanently set in a brand when we use o-brand, and this means that it doesn't work for a component that allows the user to change an aspect of the brand (https://github.com/Financial-Times/o-colors/pull/158)

**Comment by chee** [comment]
@Financial-Times/origami-core i don't understand this issue

**Comment by notlee** [comment]
I'm unsure but it sounds like a feature request for an o-brand API that will allow component/projects to add/customise brand values. Right now o-brand isn't allowed to be used by projects and brand values are set once per branded component using `oBrandDefine`, they cannot be added to or modified after that. We've got around that with component-by-component solution `oColorsSetColor`, `oTypographySetFont`, `oHeaderServicesCustomize`.

I think we can close this issue because it's quite old and we're likely to solve this problem another way. 

For example the [draft design token captures](https://github.com/Financial-Times/origami/pull/129) this as a potential benefit.
>To make it easier to customise Origami by adding new brands or variants with brands. 

We also discussed potentially adding a standardised customisation mixin in all components when we move to dart-sass modules, as the [sass docs suggest with `configure` and `styles` (aka primary mixin) mixins](https://sass-lang.com/documentation/at-rules/use#with-mixins) mixins, which might be something we want to do still
